### ISSUE TITLE
Error in running MLE example 

### ISSUE THREAD

**Issue by xxlya** [benedekrozemberczki/shapley#1]
Thank you for sharing your great work. I truly enjoyed reading it. However, I met an error when I tried the example. It seems to be fine for the MC example.

$ python multilinear_extension_example.py 
RuntimeWarning: invalid value encountered in true_divide
  self._Phi = self._Phi / np.sum(self._Phi, axis=1).reshape(-1, 1)
Traceback (most recent call last):
  File "multilinear_extension_example.py", line 11, in <module>
    solver.solve_game(W, q)
  File "/lib/python3.6/site-packages/shapley/solvers/multilinear_extension.py", line 34, in solve_game
    self._run_sanity_check(W, self._Phi)
  File "/lib/python3.6/site-packages/shapley/solution_concept.py", line 28, in _run_sanity_check
    self._verify_distribution(Phi)
  File "/lib/python3.6/site-packages/shapley/solution_concept.py", line 22, in _verify_distribution
    assert np.sum(Phi) - Phi.shape[0] < 0.001
AssertionError

**Comment by benedekrozemberczki** [comment]
I will take a look, this seems to be troubling.

Bests,

Benedek

**Comment by benedekrozemberczki** [comment]
Dear @xxlya 

I have fixed the library, the MLE approximation works fine. Please update your package version via pip.

 If you like the library please star the repo and follow me on github.

Bests,

Benedek
